server:
  port: ${PORT:8081}

spring:
  main:
    allow-circular-references: true
  application:
    name: product-api
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/product-db
    username: admin
    password: postgres
    initialization-mode: always
    initialize: true
    continue-on-error: true
    platform: postgresql
    maxActive: 3
  jpa:
    hibernate:
      ddl-auto: create-drop
      format_sql: true
    show_sql: true
    porperties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQL9Dialect

app-config:
  secrets:
   api-secret: ${API_SECRET:YXV0aC1hcGktYXBwLXNhbGVzLXN5c3RlbS1qYXZhc2NyaXB0LW5vZGVqcy1qYXZhLXJhYmJpdG1x}


