INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (1, 'Comic Books')
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (2, 'Movies')
INSERT INTO CATEGORY (ID, DESCRIPTION) VALUES (3, 'Books')

INSERT INTO SUPPLIER (ID, NAME) VALUES (1, 'Panini Comics')
INSERT INTO SUPPLIER (ID, NAME) VALUES (2, 'DC Comics')
INSERT INTO SUPPLIER (ID, NAME) VALUES (3, 'Amazon')

INSERT INTO PRODUCT (ID, NAME, FK_CATEGORY, FK_SUPPLIER, QUANTITY_AVAILABLE) VALUES (1, 'Crisis on Infinite Earths', 1, 1, 10)
INSERT INTO PRODUCT (ID, NAME, FK_CATEGORY, FK_SUPPLIER, QUANTITY_AVAILABLE) VALUES (2, 'Interestelar', 2, 3, 5)
INSERT INTO PRODUCT (ID, NAME, FK_CATEGORY, FK_SUPPLIER, QUANTITY_AVAILABLE) VALUES (3, 'Harry Potter and the Sorcerers Stone', 3, 3, 3)
